export const CATEGORY = {
    CREATE: "CREATE_CATEGORY",
    DELETE: "DELETE_CATEGORY",
    ALL_CATEGORIES: "ALL_CATEGORIES"
};
export const POST = {
    CREATE : "CREATE_POST",
    UPVOTE : "UPVOTE_POST",
    DOWNVOTE : "DOWNVOTE_POST",
    DELETE : "DELETE_POST"
};

export const COMMENT = {
    CREATE : "CREATE_COMMENT",
    UPVOTE : "UPVOTE_COMMENT",
    DOWNVOTE : "DOWNVOTE_COMMENT",
    DELETE : "DELETE_COMMENT"
};